export const GET_AIRLINE = "GET_AIRLINE";
export const GET_PASSENGER = "GET_PASSENGER";
export const ADD_PASSENGER = "ADD_RPASSENGER";
export const GET_SINGLE_PASSENGER = "GET_SINGLE_PASSENGER";
export const EDIT_PASSENGER = "EDIT_PASSENGER";
export const DELETE_PASSENGER = "DELETE_PASSENGER";
